### ISSUE TITLE
Clamav pods will not start

### ISSUE THREAD

**Issue by devinleighsmith** [bcgov/clamav-mirror#10]
#### Describe the bug

All attempts to start the image, either via the dc or via the cronjob fail with the following:

Current contents in /mnt/cvdupdate/databases directory...
ls: /mnt/cvdupdate/databases: No such file or directory

the ls command failing to find the folder appears to cause the pod to terminate.

This is a problem since all of the entrypoint.sh commands appear to run the show_config function, so there is no way to populate the /mnt/cvdupdate/databases folder, as show_config will run first and cause the pod to terminate.

This seems odd since it would seem that the above error would prevent any consumer of this repo from running the image successfully, so maybe I'm missing something?

#### To Reproduce

1. Create and run the BC
2. Retag the generated image to the target namespace
3. Create the DC in the target namespace
4. All of the DC pods will crashloop
5. Create the CronJob in the target namespace
6. Every instance of the Cronjob execution will crashloop

#### Expected behavior

the entrypoint should provide a command to perform initial setup so the expected folder is created in the volume. That would allow the image to start

#### Screenshots

![image](https://user-images.githubusercontent.com/41091511/180054115-9047e883-ecc5-44f4-942b-0b8d21fb6b9f.png)

**Comment by devinleighsmith** [comment]
I was able to work around this issue by manually connecting another image to the volume and adding and empty databases directory. Seems like a simple thing to fix in the entrypoint. Let me know if I've interpreted this error correctly and I'll create a PR

**Comment by jujaga** [comment]
Hi @devinleighsmith I presume you followed the deployment instructions from the documentation [here](https://github.com/bcgov/clamav-mirror/tree/master/openshift#build-config--deployment). I just quickly checked `entrypoint.sh` as well and I agree that there should be an if block escape check to determine if the `$CVD_DIR/databases` folder is present, and if it isn't, do a quick mkdir before continuing. This should probably be inserted into the show_config function between https://github.com/bcgov/clamav-mirror/blob/01b04e3f673fbb070cb704705e5c84c635662a7f/docker/src/entrypoint.sh#L17-L18 before it does the ls command.

If you would like to create a PR for this that would be 👍 .

That being said, we should probably have a broader quick conversation offline as to why this mirror needs to be stood up within your own namespace. You can reach out to me on RocketChat (same user handle).

**Comment by jujaga** [comment]
This has been partially addressed I think in https://github.com/bcgov/clamav-mirror/pull/11. Please take a look and see if the issue is still present.
